name = "LITS"
uuid = "86b0dc02-7903-11e9-325f-f195ca7e6c1a"
version = "0.1.0"

[deps]
DiffEqBase = "2b5f629d-d688-5b77-993f-72d75c75574e"
DiffEqCallbacks = "459566f4-90b8-5000-8ac3-15dfb0a30def"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NLsolve = "2774e3e8-f4cf-5e23-947b-6d7e65073b56"
PowerSystems = "bcd98974-b02a-5e2f-9ee0-a103f5c450dd"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Sundials = "c3572dad-4567-51f8-b174-8c6c989267f4"

[compat]
DiffEqBase = "~6.3.1"
DiffEqCallbacks = "~2.8"
NLsolve = "~4.1"
PowerSystems = "~v0.4"
Sundials = "~3.7.0"
julia = "^1.2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
