name = "PowerSimulationsDynamics"
uuid = "398b2ede-47ed-4edc-b52e-69e4a48b4336"
authors = ["Jose Daniel Lara, Rodrigo Henriquez"]
version = "0.6.3"

[deps]
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
DiffEqBase = "2b5f629d-d688-5b77-993f-72d75c75574e"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
InfrastructureSystems = "2cd47ed4-ca9b-11e9-27f2-ab636a7671f1"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LogExpFunctions = "2ab3a3ac-af41-5b50-aa03-7779005ae688"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
NLsolve = "2774e3e8-f4cf-5e23-947b-6d7e65073b56"
PowerSystems = "bcd98974-b02a-5e2f-9ee0-a103f5c450dd"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
DiffEqBase = "6"
DocStringExtensions = "~0.8.2"
ForwardDiff = "~v0.10"
InfrastructureSystems = "^1.12"
LogExpFunctions = "0.3"
NLsolve = "4"
PowerSystems = "^1.11"
SciMLBase = "1.18"
julia = "^1.6"
