[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DocumenterTools = "35a29f4d-8980-5a13-9543-d66fff28ecb8"
PowerSimulationsDynamics = "398b2ede-47ed-4edc-b52e-69e4a48b4336"
PowerSystems = "bcd98974-b02a-5e2f-9ee0-a103f5c450dd"
